PrecursorAction.C code cleanup
arfc/moltres pull request #145
Opened 2021-01-06 11:17 UTC by smpark7

Closes #139 

After reviewing PrecursorAction.C,
- I introduced the ```setVarNameAndBlock``` function to remove some repeating code. Further attempts to "DRY" would only complicate the code and affect human readability.
- I refactored the action functions and separated them based on their "physics"/"purpose" (e.g. ```kernelAct()``` -> ```addPrecursorSource()``` + ```addPrecursorDecay()``` + etc.). The main ```act()``` function now holds more if-else logic explicitly for better readability
- Removed some unnecessary vertical whitespaces

There is no change in how PrecursorAction evaluates precursor concentration => All existing tests should pass

2021-01-14 15:15 UTC, katyhuff requested changes
Great job @smpark7 !  Some minor comments included in this review, but nothing major.

2021-01-14 17:49 UTC, robfairh commented on src/actions/PrecursorAction.C
> +                                              "Kernel block can be different from block.");
I am not sure. Precursor block maybe?

2021-01-15 08:46 UTC, smpark7 commented on src/actions/PrecursorAction.C
> +    {
Yes that makes sense. I'll change all of the ```_current_task``` ifs to elseifs and remove unnecessary braces

2021-01-15 08:55 UTC, smpark7 commented on src/actions/PrecursorAction.C
> +      if (getParam<bool>("loop_precs"))
Sounds good. I'll make that change. I'll also have to edit the test input files but I think it's worth the hassle

2021-01-15 08:56 UTC, smpark7 commented on src/actions/PrecursorAction.C
> +      // Set up initial conditions for precursor conc
Got it. I'll rename it into something like ```addInitialConditions```

2021-01-15 09:27 UTC, smpark7 commented on src/actions/PrecursorAction.C
> +      // Set up MultiAppTransfer to simulate precursor looped flow into and
Yes it is. I'll make them consistent by naming both MultiAppTransfer. Naming one of them FlowTransfer seems unnecessary

2021-01-15 09:31 UTC, smpark7 commented on src/actions/PrecursorAction.C
> +    addSaltOutflowPostprocessor();
That's a really good point. I had not considered that there could be other reactor designs with moving precursors (other than perhaps the certain pebble bed reactors).

2021-01-19 16:24 UTC, smpark7 commented
Thank you for your review @katyhuff 

I've made the following changes based on your review comments:
- Appropriate changes from ```if``` to ```else if``` involving the ```_current_task ==``` loop
- Renaming functions and variables to make them more intuitive and removing explicit references to salt
- Improving/Adding docstrings for functions and variables
- Made most functions in ```PrecursorAction``` non-virtual because it isn't meant to be a base class

2021-01-28 14:27 UTC, katyhuff commented on src/actions/PrecursorAction.C
> +      // Set up MultiAppTransfer to simulate precursor looped flow into and
Thanks!

2021-01-28 14:28 UTC, katyhuff commented on src/actions/PrecursorAction.C
> +PrecursorAction::addDGAdvection(const std::string & var_name)
This seems to have been handled, yes? If so, please 'resolve' conversation. Thanks.

2021-01-28 14:29 UTC, katyhuff commented on src/actions/PrecursorAction.C
> +PrecursorAction::addOutflowBC(const std::string & var_name)
This seems like it's probably been handled. If so, please 'resolve' conversation.

2021-01-28 14:29 UTC, katyhuff commented on src/actions/PrecursorAction.C
> +PrecursorAction::addDGAdvection(const std::string & var_name)
nvm, found it. Resolved! Thanks!

2021-01-28 14:30 UTC, katyhuff approved these changes
Looks good to me! Any remaining issues @smpark7 or @robfairh ?  I'd say this is ready to merge.

2021-01-28 14:43 UTC, smpark7 commented
Thank you @katyhuff! @robfairh feel free to merge it unless you spot another issue

2021-01-28 18:39 UTC, robfairh approved these changes
Katy's review was very thorough!

2021-01-28 18:40 UTC, merged