CNRS benchmark results (Step 0.1, 0.2, 0.3)
arfc/moltres pull request #151
Opened 2021-03-03 17:12 UTC by smpark7

This PR adds Moltres input files to run the CNRS benchmark. The CNRS benchmark is a multiphysics benchmark for MSR simulation software. More details about the CNRS benchmark can be found in "_Results from a multi-physics numerical benchmark for codes dedicated to molten salt fast reactors_" ([DOI](https://doi.org/10.1016/j.anucene.2020.107428)).

This PR contains:
- Cross section data provided from the benchmark and readable by Moltres in the ```property_file_dir/cnrs-directory``` subdirectory
- ```property_file_dir/cnrs-directory/feedback.py``` applies thermal salt expansion feedback to the cross section data
- Moltres input files for Step 0.1, 0.2, and 0.3 of the CNRS benchmark
- A template of the job script used to run the simulations on Blue Waters (```problems/2021-cnrs-benchmark/bw_job_script.pbs```)
- READMEs in each subdirectory

As mentioned in the README, I highly advise running Steps 0.2 and 0.3 on Blue Waters because they're computationally and/or memory intensive. I will add the files for the remaining Steps in the benchmark in a later PR.

2021-03-04 08:58 UTC, smpark7 commented
Civet is throwing out an error that's unrelated to the changes here. I suspect that there were changes to the MOOSE environment related to cppunit

2021-03-04 12:00 UTC, robfairh requested changes
A couple of comments. I'll keep looking for other things later.

2021-03-04 12:45 UTC, smpark7 commented on property_file_dir/cnrs-benchmark/feedback.py
> +    xs_names = ["DIFFCOEF", "FISS", "NSF", "REMXS", "SP0"]
Thanks for reviewing my PR! Yea I'll include the script and the data at 900K and update the readme.

I'll include the journal article I got the cross sections from as well.

2021-03-05 16:33 UTC, pep8speaks commented
Hello @smpark7! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`property_file_dir/cnrs-benchmark/feedback.py`](https://github.com/arfc/moltres/blob/4f840feefb0f0fa99895a0920ed2b7c9ec3519c4/property_file_dir/cnrs-benchmark/feedback.py):

> [Line 11:1](https://github.com/arfc/moltres/blob/4f840feefb0f0fa99895a0920ed2b7c9ec3519c4/property_file_dir/cnrs-benchmark/feedback.py#L11): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2021-03-11 10:35 UTC, smpark7 commented
Thanks @robfairh for your comments and suggestions. I've incorporated your suggestions and this PR is ready to another review.

2021-03-12 11:48 UTC, robfairh approved these changes
Great! Good job!

2021-03-12 11:48 UTC, merged