Refactor material source code, and add error checks and tests
arfc/moltres pull request #230
Opened 2023-03-06 23:19 UTC by smpark7

This PR introduces the following changes:
- Refactor parent class `NuclearMaterial` and its child classes `GenericMoltresMaterial` and `MoltresJsonMaterial` to reduce code duplication.
  - Combine `dummyConstruct`, `splineConstruct`, `linearConstruct`, and `monotoneCubicConstruct` functions into a single `Construct` function in `GenericMoltresMaterial`.
  - Standardize the use of inherited `_xsec_map` and `_xsec_names` variables in `GenericMoltresMaterial` and `MoltresJsonMaterial` for common interpolation schemes (`NONE`, `LINEAR`, `SPLINE`, `MONOTONE_CUBIC`).
  - Bug fix: Don't apply linear interpolation in `MoltresJsonMaterial` if user sets `interp_type=none`.
- Add error checks to `GenericMoltresMaterial` and `MoltresJsonMaterial` to check whether the number of group constant data values matches the `num_groups` and `num_precursor_groups` parameters provided by the user.
- Add tests for `GenericMoltresMaterial` and `MoltresJsonMaterial` that test whether the material objects initialize correctly, or provide the intended error message otherwise.
- Remove unnecessary Precursor modeling in DiracHX test to avoid running into the new materials error checks.

***Note: The interpolation types follow MOOSE standard language:
- `NONE`: No interpolation
- `LINEAR`: Linear spline interpolation
- `SPLINE`: Cubic spline interpolation
- `MONOTONE_CUBIC`: Monotone cubic interpolation

2023-03-07 18:20 UTC, samgdotson requested changes
This looks much cleaner, good job @smpark7! I’m wondering if some of these binary files are actually built files or pre-compiled? If they’re built files they should be removed, if they’re pre compiled then that’s fine. Happy to merge once this is clarified (unless you want others to review as well).

2023-03-07 18:59 UTC, smpark7 commented
Thanks for the quick review @samgdotson! The binary files are all Exodus (.e) output files in `gold` directories. They're reference results that some of the new tests compare against. So I think they're what you consider pre-compiled files.

Let's leave it unmerged until tomorrow to give others a chance to review. I'll ping you if necessary.

2023-03-08 21:02 UTC, LukeSeifert approved these changes
This looks good, I just had two small things I noticed.

2023-03-08 22:32 UTC, smpark7 commented on src/materials/GenericMoltresMaterial.C
> +                "The number of " + _file_map[_xsec_names[j]] + " values does not match "
The subject is "The number of" so I believe it's singular.

2023-03-08 22:48 UTC, smpark7 commented on src/materials/NuclearMaterial.C
> +    _d_gtransfxs_d_temp[_qp][i] = _xsec_map["GTRANSFXS"][i][0];
In this case, the user provides group constant data at only one temperature. Taking the derivative with respect to temperature doesn't make sense, but this variable is required by Moltres kernels. I can't think of an elegant way to make `_d_gtransfxs_d_temp` optional, so I'm keeping the existing behavior of passing the same value.

2023-03-09 17:19 UTC, smpark7 commented
@samgdotson This is ready for merging now

2023-03-09 17:24 UTC, samgdotson approved these changes
lgtm

2023-03-09 17:24 UTC, merged