Add diffusion theory and associated kernels to Theory page on Moltres website
arfc/moltres pull request #270
Opened 2024-05-28 19:24 UTC by nglaser3

## Summary of changes

Add brief introduction to multi-group diffusion in Moltres, add table of terms in multi group diffusion equation and their associated kernels, add table of terms in delayed neutron precursor equation and their associated kernels. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Required for Merging
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
  - [ ] CI tests pass

## Associated Issues and PRs

- Resolves #267 

## Associated Developers

- Dev: @smpark7 

## Checklist for Reviewers

Reviewers should use [this link](https://arfc.github.io/manual/guides/pull_requests) to get to the 
Review Checklist before they begin their review.

2024-05-29 19:52 UTC, smpark7 commented
Hey @nglaser3, great work here! Before I provide specific review comments, could you break up your paragraphs into multiple lines with a max limit of 100 characters per line? This will help with indicating which parts of the text my review comments are referring to.

You can leave an empty line between the paragraphs to maintain separation in the rendered html file.

2024-05-29 21:13 UTC, nglaser3 commented
@smpark7, Thank you! I have broken the paragraphs into sentences, and checked to make sure the formatting was still correct. Please let me know if there are any other pre-check changes you would like me to make!

2024-05-30 20:16 UTC, smpark7 requested changes
Good work on writing up this draft! I included several comments for typos and to improve the general flow.

General comments:
- Remove spaces at the end of lines
- Limit line lengths to 100 characters
- Use MooseDoc-style links for the kernel links

2024-05-30 20:16 UTC, smpark7 commented on doc/content/getting_started/theory.md
> +The first term describes the neutrons immediately born from fission, and the second term describes the neutrons born from the radioactive decay of neutron-emitting radionuclides, commonly called dela
Move these to the top of the second paragraph

2024-05-30 20:16 UTC, smpark7 commented on doc/content/getting_started/theory.md
> +Discretization with respect to time is accomplished with discrete time-steps.
```suggestion
In FEM, the spatial domain is discretized into finite mesh elements while the time dependence is modeled through discrete time steps and time integration methods.
```

2024-05-30 20:16 UTC, smpark7 commented on doc/content/getting_started/theory.md
> +The governing equation for the delayed neutron precursor population:
```suggestion
The governing equation for the delayed neutron precursor distribution is:
```

2024-05-30 22:36 UTC, smpark7 requested changes
It looks good overall. I noted a few more corrections to be made.

2024-05-30 22:36 UTC, smpark7 commented on doc/content/getting_started/theory.md
> +A full derivation of the diffusion equation will not be presented here for conciceness. Importantly, when taking the first moment of the transport equation the angular flux is assumed to be linearly
```suggestion
A full derivation of the diffusion equation will not be presented here for conciseness. Importantly, when taking the first moment of the transport equation the angular flux is assumed to be linearly anisotropic. 
```

2024-05-30 22:36 UTC, smpark7 commented on doc/content/getting_started/theory.md
> +As a dertiministic method, the neutron diffusion method also requires discretization of the continuous energy dependence into energy groups consisting of non-overlapping, finite energy ranges across
```suggestion
As a deterministic method, the neutron diffusion method also requires discretization of the continuous energy dependence into energy groups consisting of non-overlapping, finite energy ranges across the entire energy spectrum. 
```

2024-05-30 22:36 UTC, smpark7 commented on doc/content/getting_started/theory.md
> +where the precursor distributions are governed by:
```suggestion
The delayed neutron precursor distributions are governed by:
```

2024-05-30 22:36 UTC, smpark7 commented on doc/content/getting_started/theory.md
> +
```suggestion
```
Remove extra empty line here

2024-05-31 00:55 UTC, smpark7 approved these changes
Good work Nathan!

2024-05-31 00:56 UTC, smpark7 commented
@katyhuff @munkm Do you have any comments to add?

2024-06-03 15:12 UTC, katyhuff commented
100 characters per line is still pretty long. Usually we go with 80. @smpark7 is there a reason for 100?

2024-06-05 01:06 UTC, merged